name: unit-test
description: "Runs the unit tests on GdUnit4 API"

inputs:
    test-includes:
        description: "The path to include tests to be run"
        required: true
    godot-bin:
        description: "The path to the godot binary"
        required: true

runs:
    using: composite

    steps:
        - name: "Unit Test Linux"
          if: ${{ runner.OS == 'Linux' }}
          env:
              GODOT_BIN: "/home/runner/godot-linux/godot"
          shell: bash
          run: |
              chmod +x ./addons/gdUnit4/runtest.sh
              xvfb-run --auto-servernum ./addons/gdUnit4/runtest.sh --add ${{ inputs.test-includes }} --audio-driver Dummy --display-driver x11 --rendering-driver opengl3 --screen 0 --continue --verbose
