name: ci-dev

on:
    push:
        branches:
            - main
        paths-ignore:
            - "*" # Ignore all files until workflow for tests is fixed
            - "**.yml"
            - "**.jpg"
            - "**.png"
            - "**.svg"
            - "**.md"
            - "**plugin.cfg"
    workflow_dispatch:

concurrency:
    group: ci-dev-${{ github.event.number }}
    cancel-in-progress: true

jobs:
    unit-tests:
        permissions: write-all

        strategy:
            fail-fast: false
            max-parallel: 10
            matrix:
                godot-version: ["4.2.1"]

        name: "CI on Godot 🐧 v${{ matrix.godot-version }}-stable"
        uses: ./.github/workflows/unit-tests.yml
        with:
            godot-version: ${{ matrix.godot-version }}
            godot-status: "stable"
